/**
 * User roles in the application
 */
export type Role = 'Buyer' | 'Seller';

/**
 * Navigation types will be auto-generated by Expo Router
 * when experiments.typedRoutes is enabled
 */

/**
 * Auth context type
 */
export interface AuthContextType {
  role: Role | null;
  setRole: (role: Role | null) => void;
  logout: () => void;
  isLoading: boolean;
}

/**
 * Product types (will be refined based on SDK types)
 */
export interface Product {
  _id: string;
  Title: string;
  Description?: string;
  Price: number;
  MRP?: number;
  Category: string;
  Stock: number;
  ImageUrl?: string;
  Brand?: string;
  Warehouse?: string;
  [key: string]: any; // For additional SDK fields
}

/**
 * Cart item type
 */
export interface CartItem {
  _id: string;
  productId: string;
  productName: string;
  productPrice: { value: number; currency: string };
  productImage: string;
  quantity: number;
  subtotal?: number;
}
